name: Docker image build

on: 
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - 'master'

jobs:

  test_python:
    name: test_python
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python 3.9'
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64, arm, 386]
    steps:
    - uses: actions/checkout@v2

    - name: prepare multiarch
      run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2.2.1
      with:
        image: foaas-slack
        archs: ${{ matrix.arch }}
        tags: latest-${{ matrix.arch }}
        dockerfiles: |
          ./Dockerfile