name: Docker image build

on: 
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, arm, 386]
    steps:
    - uses: actions/checkout@v2

    - name: prepare multiarch
      run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
        image: foaas-slack
        archs: $ {{ matrix.arch }}
        dockerfiles: |
          ./Dockerfile