name: Docker image build

on: 
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Run Image
      runs:
      using: 'docker'
      image: 'Dockerfile'